// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mboecmnqkopphvmpsgyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ib2VjbW5xa29wcGh2bXBzZ3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODY1NDgsImV4cCI6MjA2NTg2MjU0OH0.5cDXqGXM8eoNTGccNC2P2RYbx77fDBypdcNsKSV79SE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);